#!/usr/bin/env python3
"""
generate-infographic.py
Localized changelog infographic generator using Pillow

Usage: python3 generate-infographic.py <input.json> <lang> <output.png>
"""

import json
import sys
import os
import platform
from PIL import Image, ImageDraw, ImageFont

# ===== Localization =====
L10N = {
    'en': {
        'update_title': 'Claude Code Update',
        'version_upgrade': 'Version Upgrade',
        'new_features': 'New Features',
        'improvements': 'Improvements & Fixes',
        'tip': 'TIP',
        'fix': 'FIX',
        'generated_by': 'Generated by cc-version-updater',
    },
    'ja': {
        'update_title': 'Claude Code アップデート',
        'version_upgrade': 'バージョンアップ',
        'new_features': '新機能',
        'improvements': '改善・修正',
        'tip': 'ヒント',
        'fix': '修正',
        'generated_by': 'cc-version-updater で生成',
    },
    'zh': {
        'update_title': 'Claude Code 更新',
        'version_upgrade': '版本升级',
        'new_features': '新功能',
        'improvements': '改进和修复',
        'tip': '提示',
        'fix': '修复',
        'generated_by': '由 cc-version-updater 生成',
    },
    'ko': {
        'update_title': 'Claude Code 업데이트',
        'version_upgrade': '버전 업그레이드',
        'new_features': '새 기능',
        'improvements': '개선 및 수정',
        'tip': '팁',
        'fix': '수정',
        'generated_by': 'cc-version-updater로 생성됨',
    },
}


def hex_to_rgb(hex_color):
    """Convert hex color to RGB tuple."""
    hex_color = hex_color.lstrip('#')
    return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))


def get_font(size, lang='en'):
    """Get Unicode-compatible font based on platform and language."""
    font_paths = []

    if platform.system() == "Darwin":  # macOS
        if lang in ('ja', 'zh', 'ko'):
            font_paths = [
                "/System/Library/Fonts/ヒラギノ角ゴシック W3.ttc",
                "/System/Library/Fonts/ヒラギノ角ゴシック W6.ttc",
                "/System/Library/Fonts/Hiragino Sans GB.ttc",
                "/System/Library/Fonts/PingFang.ttc",
                "/System/Library/Fonts/AppleSDGothicNeo.ttc",
            ]
        font_paths.extend([
            "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
            "/System/Library/Fonts/Helvetica.ttc",
        ])
    elif platform.system() == "Linux":
        font_paths = [
            "/usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc",
            "/usr/share/fonts/google-noto-cjk/NotoSansCJK-Regular.ttc",
            "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        ]
    elif platform.system() == "Windows":
        font_paths = [
            "C:/Windows/Fonts/yugothic.ttf",
            "C:/Windows/Fonts/meiryo.ttc",
            "C:/Windows/Fonts/msyh.ttc",
            "C:/Windows/Fonts/malgun.ttf",
            "C:/Windows/Fonts/arial.ttf",
        ]

    for path in font_paths:
        try:
            return ImageFont.truetype(path, size)
        except Exception:
            continue

    # Fallback to default
    try:
        return ImageFont.load_default()
    except Exception:
        return None


def parse_changelog(changelog_text):
    """Parse changelog markdown to extract features and improvements."""
    lines = changelog_text.split('\n')
    features = []
    improvements = []

    for line in lines:
        trimmed = line.strip()
        if trimmed.startswith('- Added') or 'support' in trimmed.lower() or 'tool' in trimmed.lower():
            if trimmed.startswith('- '):
                text = trimmed[2:]
                if text.startswith('Added '):
                    text = text[6:]
                words = text.split()
                features.append({
                    'name': ' '.join(words[:4]),
                    'description': text[:80],
                })
        elif trimmed.startswith('- Fixed') or trimmed.startswith('- Improved'):
            if trimmed.startswith('- '):
                text = trimmed[2:]
                if text.startswith('Fixed '):
                    text = text[6:]
                elif text.startswith('Improved '):
                    text = text[9:]
                improvements.append(text[:80])

    return features[:5], improvements[:6]


def create_infographic(data, lang, output_path):
    """Create localized changelog infographic."""
    l = L10N.get(lang, L10N['en'])

    # Parse changelogs
    all_features = []
    all_improvements = []

    for entry in data.get('changelogs', []):
        changelog_text = entry.get('changelog', '')
        features, improvements = parse_changelog(changelog_text)
        all_features.extend(features)
        all_improvements.extend(improvements)

    # Limit items
    all_features = all_features[:5]
    all_improvements = all_improvements[:6]

    # Calculate height
    base_height = 400
    feature_height = len(all_features) * 140
    improvement_height = len(all_improvements) * 35
    height = base_height + feature_height + improvement_height + 100
    height = min(max(height, 600), 1600)

    width = 1200

    # Colors (dark theme)
    bg_color = hex_to_rgb("#0F172A")
    card_bg = hex_to_rgb("#1E293B")
    accent_blue = hex_to_rgb("#3B82F6")
    accent_orange = hex_to_rgb("#F97316")
    accent_green = hex_to_rgb("#10B981")
    text_white = hex_to_rgb("#F8FAFC")
    text_muted = hex_to_rgb("#94A3B8")
    gradient_start = hex_to_rgb("#1E40AF")

    # Create image
    img = Image.new("RGB", (width, height), bg_color)
    draw = ImageDraw.Draw(img)

    # Fonts
    font_title = get_font(42, lang)
    font_section = get_font(26, lang)
    font_heading = get_font(20, lang)
    font_body = get_font(16, lang)
    font_small = get_font(14, lang)

    margin = 60
    y = 30

    # === HEADER with gradient ===
    for i in range(140):
        alpha = 1 - (i / 140) * 0.8
        r = int(gradient_start[0] * alpha + bg_color[0] * (1 - alpha))
        g = int(gradient_start[1] * alpha + bg_color[1] * (1 - alpha))
        b = int(gradient_start[2] * alpha + bg_color[2] * (1 - alpha))
        draw.line([(0, i), (width, i)], fill=(r, g, b))

    # Title
    if font_title:
        draw.text((margin, 35), l['update_title'], font=font_title, fill=text_white)

    # Version transition
    prev_version = data.get('previousVersion', '?')
    latest_version = data.get('latestVersion', '?')
    version_text = f"v{prev_version}  -->  v{latest_version}"
    if font_section:
        draw.text((margin, 90), version_text, font=font_section, fill=accent_orange)

    y = 170

    # === NEW FEATURES SECTION ===
    if all_features:
        if font_section:
            draw.text((margin, y), l['new_features'], font=font_section, fill=text_white)
        y += 45

        for i, feature in enumerate(all_features):
            # Card background
            card_rect = [margin, y, width - margin, y + 120]
            draw.rounded_rectangle(card_rect, radius=12, fill=card_bg)

            # Number badge
            badge_x = margin + 20
            badge_y = y + 20
            draw.ellipse([badge_x, badge_y, badge_x + 36, badge_y + 36], fill=accent_blue)
            if font_heading:
                # Center the number in badge
                draw.text((badge_x + 12, badge_y + 6), str(i + 1), font=font_heading, fill=text_white)

            # Feature name
            if font_heading:
                draw.text((margin + 75, y + 25), feature.get('name', '')[:40], font=font_heading, fill=text_white)

            # Description
            if font_body:
                desc = feature.get('description', '')[:75]
                draw.text((margin + 75, y + 60), desc, font=font_body, fill=text_muted)

            # Tip indicator
            if font_small:
                draw.text((margin + 75, y + 90), f"[{l['tip']}]", font=font_small, fill=accent_green)

            y += 140

    # === IMPROVEMENTS SECTION ===
    if all_improvements:
        y += 20
        if font_section:
            draw.text((margin, y), l['improvements'], font=font_section, fill=accent_green)
        y += 45

        for imp in all_improvements:
            if font_body:
                draw.text((margin + 20, y), f"- {imp[:70]}", font=font_body, fill=text_muted)
            y += 35

    # === FOOTER ===
    footer_y = height - 50
    draw.line([(margin, footer_y - 10), (width - margin, footer_y - 10)], fill=hex_to_rgb("#334155"), width=1)
    if font_small:
        draw.text((margin, footer_y), l['generated_by'], font=font_small, fill=text_muted)

    # Save
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    img.save(output_path, "PNG", quality=95)

    return output_path


def main():
    if len(sys.argv) < 4:
        print("Usage: generate-infographic.py <input.json> <lang> <output.png>", file=sys.stderr)
        sys.exit(1)

    input_path = sys.argv[1]
    lang = sys.argv[2]
    output_path = sys.argv[3]

    try:
        with open(input_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception as e:
        print(f"Error reading input: {e}", file=sys.stderr)
        sys.exit(1)

    try:
        result = create_infographic(data, lang, output_path)
        print(f"[OK] Generated: {result}")
    except Exception as e:
        print(f"Error generating infographic: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
